### ISSUE TITLE
Hidden files not present in npm package

### ISSUE THREAD

**Issue by cbornet** [pascalgrimaud/generator-jhipster-module#1]
I got an error while creating a module because .gitignore was not found in node_modules

**Comment by pascalgrimaud** [comment]
oh maybe I should rename `.gitignore` to `gitignore` and all other .<file> to <file>

**Comment by pascalgrimaud** [comment]
Don't understand. The rename didn't resolve it !

**Comment by pascalgrimaud** [comment]
Temporarily, the .files are not generated, but the module can be used => release v0.0.5
So you can update the module

I'll have a look on this issue asap

**Comment by pascalgrimaud** [comment]
It should be fix in v0.0.6. The package is published.
Can you have a try and confirm it works for you ?
